// Generated by CoffeeScript 1.6.3
var americano, port;

americano = require('americano');

port = process.env.PORT || 9250;

americano.start({
  name: 'cozy-files',
  port: port
}, function(app, server) {
  return app.server = server;
});
