// Generated by CoffeeScript 1.6.3
var logwatch, patch1, port, start;

patch1 = require('./server/initializers/patch1');

logwatch = require('./server/initializers/finglogwatch');

start = function(port, callback) {
  return require('americano').start({
    name: 'Contacts',
    port: port
  }, function(app, server) {
    app.set('views', './client/');
    return patch1(function(err) {
      if (err) {
        return typeof callback === "function" ? callback(err) : void 0;
      }
      return logwatch(server, function(err) {
        return typeof callback === "function" ? callback(err, app, server) : void 0;
      });
    });
  });
};

if (!module.parent) {
  port = process.env.PORT || 9114;
  start(port, function(err) {
    if (err) {
      console.log("Initialization failed, not starting");
      console.log(err.stack);
      return process.exit(1);
    }
  });
} else {
  module.exports = start;
}
