// Generated by CoffeeScript 1.6.2
var Client,
  _this = this;

Client = require('request-json').JsonClient;

this.client = new Client("http://localhost:9101/");

if (process.env.NODE_ENV === "production" || process.env.NODE_ENV === "test") {
  this.client.setBasicAuth(process.env.NAME, process.env.TOKEN);
}

module.exports = function() {
  var data;

  data = {
    filter: "function (doc, req) {\n" + "    if(doc._deleted) {\n" + "        return true; \n" + "    }\n" + "    if ((doc.docType && doc.docType === \"File\") " + " || (doc.docType && doc.docType === \"Folder\")) {\n" + "        return true; \n" + "    } else { \n" + "        return false; \n" + "    }\n" + "}"
  };
  return _this.client.put("filter/filesfilter/", data, function() {});
};
