// Generated by CoffeeScript 1.6.3
var PhoneCommunicationLog, Realtimer;

PhoneCommunicationLog = require('../models/phone_communication_log');

Realtimer = require('cozy-realtime-adapter');

module.exports = function(server, next) {
  return PhoneCommunicationLog.mergeToContactLog(function(err) {
    var realtime;
    if (err) {
      return next(err);
    }
    realtime = Realtimer({
      server: server
    }, ['contact.*', 'callLog.*']);
    realtime.on('phonecommunicationlog.create', PhoneCommunicationLog.mergeToContactLogRT);
    return next(null);
  });
};
