// Generated by CoffeeScript 1.6.2
var File, americano;

americano = require('americano-cozy');

module.exports = File = americano.getModel('File', {
  path: String,
  name: String,
  slug: String,
  binary: String,
  _attachment: Object
});

File.all = function(params, callback) {
  return File.request("all", params, callback);
};

File.byFolder = function(params, callback) {
  return File.request("byFolder", params, callback);
};
