// Generated by CoffeeScript 1.6.3
var MailSent, americano;

americano = require('americano-cozy');

module.exports = MailSent = americano.getModel('MailSent', {
  createdAt: {
    type: Number,
    "default": 0
  },
  sentAt: {
    type: Number,
    "default": 0
  },
  subject: {
    type: String
  },
  from: {
    type: String
  },
  to: {
    type: String
  },
  cc: {
    type: String
  },
  bcc: {
    type: String
  },
  html: {
    type: String
  }
});
