// Generated by CoffeeScript 1.6.3
var Remote, americano;

americano = require('americano-cozy');

module.exports = Remote = americano.getModel('Remote', {
  login: String,
  password: String
});

Remote.all = function(params, callback) {
  return Remote.request("all", params, callback);
};
