// Generated by CoffeeScript 1.6.2
var americano;

americano = require('americano-cozy');

module.exports = {
  file: {
    all: function(doc) {
      return emit(doc.slug, doc);
    },
    byFolder: function(doc) {
      return emit(doc.path, doc);
    }
  },
  folder: {
    all: function(doc) {
      return emit(doc.slug, doc);
    },
    byFolder: function(doc) {
      return emit(doc.path, doc);
    }
  }
};
