// Generated by CoffeeScript 1.7.1
var americano;

americano = require('americano-cozy');

module.exports = {
  contact: {
    all: americano.defaultRequests.all
  },
  config: {
    all: americano.defaultRequests.all
  },
  contact_log: {
    all: americano.defaultRequests.all,
    bySnippet: function(doc) {
      var remote, snippet;
      remote = doc.remote.id || doc.remote.tel || doc.remote.mail;
      snippet = "" + doc.timestamp + " : " + doc.type + " ";
      snippet += "" + doc.direction + " " + remote;
      return emit(snippet, doc);
    },
    byRemote: function(doc) {
      var remote;
      remote = doc.remote.id || doc.remote.tel || doc.remote.mail;
      return emit(remote, doc);
    }
  },
  phone_communication_log: {
    all: americano.defaultRequests.all,
    bySnippet: function(doc) {
      return emit(doc.snippet, doc);
    },
    byNumber: function(doc) {
      return emit(doc.correspondantNumber, doc);
    }
  },
  todolist: {
    all: americano.defaultRequests.all
  },
  tree: {
    byType: function(doc) {
      return emit(doc.type, doc);
    }
  },
  task: {
    all: americano.defaultRequests.all
  }
};
