// Generated by CoffeeScript 1.7.1
module.exports = function(req, res, next) {
  res.error = function(code, msg, err) {
    console.log(msg);
    if (err) {
      console.log(err);
      console.log(err.stack);
    }
    res.send({
      error: msg
    }, code);
    return msg;
  };
  res.success = function(msg, code) {
    return res.send({
      success: msg
    });
  };
  return next();
};
